import { defineConfig } from 'rollup';
import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import { terser } from 'rollup-plugin-terser';
import scss from 'rollup-plugin-scss';

const isProd = process.env.BUILD === 'production';
const plugins = [typescript(), nodeResolve({ browser: true }), commonjs(), scss({ output: 'styles.css' })];

if (isProd) {
  plugins.push(terser());
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default defineConfig({
  input: 'main.ts',
  output: {
    dir: '.',
    sourcemap: isProd ? false : 'inline',
    format: 'cjs',
    exports: 'default',
    banner
  },
  external: ['obsidian'],
  plugins
});
